version: '3'

services:

  nginx:
    build: ./.build/docker/nginx
    restart: always
    ports:
      - "8008:80"
      - "4430:443"
    volumes:
      - ./:/app
      - ./.build/docker/nginx/nginx/:/etc/nginx/
    depends_on:
      - php

  php:
    build: ./.build/docker/php
    volumes:
      - ./:/app
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: monster
      MYSQL_DATABASE: freightcost
      MYSQL_USER: freightcost
      MYSQL_PASSWORD: freightcost

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: myUserPass